name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    # create edits in github tokens
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # we add this to create publish and use it
      - name: Login to Registry
        uses: docker/login-action@v3
        -name: Set image version (tag)
         id: image_version
         run: echo "gitsha=$(git reb-parse --short HEAD)" >> $GITHUB_OUTPUT

       - name: Login to Registry
         uses: docker/login-action@c3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run:
          docker build . --file Dockerfile --tag ghcr.io/husam-abuzina/express-app:$(date +%s | tr '[:upper:]' '[:lower:]')
          #should to be tag name same name of repo
       - name: publish docker image
         run: docker push ghcr.io/husam-abuzina/express-docker:${{ steps.image_version.outputs.gitsha }}
         