name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set image version (tag)
        id: image_version
        run: echo "::set-output name=gitsha::$(git rev-parse --short HEAD)"

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/husam-abuzina/express-docker:${{ steps.image_version.outputs.gitsha }}

      - name: Publish Docker image
        run: docker push ghcr.io/husam-abuzina/express-docker:${{ steps.image_version.outputs.gitsha }}
     - name: confiure docker host
       uses: husam-abuzina/configure-docker-host@v1
      with:
        host: 18.170.38.203
        user: github
        ssh-private-key: ${{ secrets.DEPLOYMENT_KEY }}
    - name: deploy
      run: docker compose -f docker-compose-prod.yml up -d
      env:
        DB_PASSWORD: ${{ secrets.DB_PASSOWRD }}
      name: print logs
      if: always()
      run: docker compose logs 

